### ISSUE TITLE
Improve graphs

### ISSUE THREAD

**Issue by m-rtijn** [m-rtijn/argostime#22]
Maybe switch to [Apache ECharts](https://echarts.apache.org/en/index.html)?

**Comment by Tweska** [comment]
I think you can also make matplotlib graphs interactive in the browser. I found this: https://mpld3.github.io/

**Comment by Tweska** [comment]
I am currently working on this in [Tweska:graph-improvements](https://github.com/Tweska/argostime/tree/graph-improvements).

**Comment by m-rtijn** [comment]
Cool @Tweska !
