### ISSUE TITLE
Browser extension to add/view product

### ISSUE THREAD

**Issue by Tweska** [m-rtijn/argostime#31]
It would be nice to have an easier way to add products and view existing data when you are visiting the shop website.

I think we can achieve this with a separate browser extension for Chrome and Firefox. Feel free to share your thoughts on this idea here. 

Some resources:
- [Mozilla Firefox extensions](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions)
- [Google Chrome extensions](https://developer.chrome.com/docs/extensions/)

**Comment by Tweska** [comment]
Functionality of the extension:
- Detect that user is visiting a product page that can potentially be crawled by Argostime.
- If product is not indexed, show a button to add the product to Argostime.
- If product is already indexed, show some statistics like current price, all-time low, all-time high and a link to the Argostime product page.

**Comment by m-rtijn** [comment]
This would be so cool!
