### ISSUE TITLE
Improve new graphs on mobile devices

### ISSUE THREAD

**Issue by m-rtijn** [m-rtijn/argostime#34]
It's not taking up all space it can/should on my phone

![Screenshot_20220416-221418_Firefox](https://user-images.githubusercontent.com/5114106/163690068-f7ff3eb3-d808-414a-b35a-227523edb956.jpg)

**Comment by Tweska** [comment]
What happens if you add this line to the head?:

```<meta name="viewport" content="width=device-width, initial-scale=1.0" />```

It should help with viewing on mobile devices in general.

**Comment by m-rtijn** [comment]
Hmmm, it helps with the graph but it zooms in so much that you can't really see the rest of the website
