### ISSUE TITLE
AH incorrect price for some discounted products

### ISSUE THREAD

**Issue by defterade** [m-rtijn/argostime#39]
E.g. 

- https://www.ah.nl/producten/product/wi513858/ah-3-laags-toiletpapier
- https://www.ah.nl/producten/product/wi417953/parodontax-original-dagelijkse-tandpasta

Will report a current price of €-1,00 and a lowest price of €9223372036854775808.00.

**Comment by Tweska** [comment]
I think this is a duplicate of issue #17.
