### ISSUE TITLE
Jumbo missing on https://argostime.mrtijn.nl/

### ISSUE THREAD

**Issue by JonathanMurre** [m-rtijn/argostime#54]
It looks like Jumbo is missing on https://argostime.mrtijn.nl/ but is available in this repository. Is https://argostime.mrtijn.nl/ in need of an update?

**Comment by m-rtijn** [comment]
This is a known issue. Jumbo's servers block access from the server on which argostime.mrtijn.nl is hosted, so it's disabled in production.
